# -*- coding: utf-8 -*-
"""Gradient_Descent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14W0Qvu4JO14k2sI5OKitX5aQKf67fxYv
"""

from sklearn.datasets import make_regression
import numpy as np
import matplotlib.pyplot as plt

x,y=make_regression(n_samples=4,n_features=1,n_informative=1,n_targets=1,noise=80,random_state=13)
plt.scatter(x,y)

#lets apply OLS
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x,y)

reg.coef_

reg.intercept_

plt.scatter(x,y)
plt.plot(x,reg.predict(x),color='red')

# Let's apply gradient descent assuming the slope is constant, m is equal to 78.35
#  And let's assume the starting value of intercept b is equal to zero.
y_pred=((78.35*x)+100).reshape(4)

plt.scatter(x,y)
plt.plot(x,reg.predict(x),color='red',label='OLS')
plt.plot(x,y_pred,color='green',label='b=100')
plt.legend()
plt.show()

m=78.35
b=100

loss_slope=-2* np.sum(y-m*x.ravel()-b)
loss_slope

# Let's take the learning rate =0.1
lr=0.1
step_size=loss_slope*lr
step_size

#Calculating new interceptors
b=b-step_size
b

y_pred1=((78.38*x)+b).reshape(4)
plt.scatter(x,y)
plt.plot(x,reg.predict(x),color='red',label='OLS')
plt.plot(x,y_pred1,color='green',label='b={}'.format(b))
plt.plot(x,y_pred,color='blue',label='b=100')
plt.legend()
plt.show()

# iteration 2
loss_slope=-2*np.sum(y-m*x.ravel()-b)
loss_slope

step_size=loss_slope*lr
step_size

b=b-step_size
b

y_pred2=((78.38*x)+b).reshape(4)
plt.scatter(x,y)
plt.plot(x,reg.predict(x),color='red',label='OLS')
plt.plot(x,y_pred1,color='green',label='b={}'.format(b))
plt.plot(x,y_pred2,color='pink',label='b={}'.format(b))
plt.plot(x,y_pred,color='blue',label='b=0')
plt.legend()
plt.show()

# iteration 3
loss_slope=-2*np.sum(y-m*x.ravel()-b)
loss_slope

step_size=loss_slope*lr
step_size

b=b-step_size
b

y_pred3=((78.38*x)+b).reshape(4)
plt.scatter(x,y)
plt.plot(x,reg.predict(x),color='red',label='OLS')
plt.plot(x,y_pred1,color='green',label='b={}'.format(b))
plt.plot(x,y_pred2,color='pink',label='b={}'.format(b))
plt.plot(x,y_pred3,color='black',label='b={}'.format(b))
plt.plot(x,y_pred,color='blue',label='b=0')
plt.legend()
plt.show()

# This can be done using loop
b=-100
m=78.35
lr=0.1

epochs=10

for i in range(epochs):
  loss_slope=-2*np.sum(y-m*x.ravel()-b)
  b=b-(lr*loss_slope)

  y_pred4=m*x+b

  plt.plot(x,y_pred4)
plt.scatter(x,y)

"""# MY_Class"""

from sklearn.datasets import make_regression
import matplotlib.pyplot as plt
import numpy as np

x,y=make_regression(n_samples=100,n_features=1,n_informative=1,n_targets=1,noise=20)
plt.scatter(x,y)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(x,y)
lr.coef_

lr.intercept_

class GDRegressor:
  def __init__(self, learning_rate, epochs):
    self.m=34.289
    self.b=0.381
    self.lr=learning_rate
    self.epochs=epochs

  def fit(self,x,y):
    for i in range(self.epochs):
      loss_slope=-2*np.sum(y-self.m*x.ravel()-self.b)
      self.b=b-(lr*loss_slope)
      y_pred4=m*x+b
    print(self.b)

gd=GDRegressor(0.1,10)

# gd.fit(x,y)

"""## Gradient Descent with calculating m and b both"""

from sklearn.datasets import make_regression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score

x,y=make_regression(n_samples=100,n_features=1,n_informative=1,n_targets=1,noise=20,random_state=13)
plt.scatter(x,y)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(x,y)
print(lr.coef_)
print(lr.intercept_)

np.mean(cross_val_score(lr,x,y,scoring="r2",cv=10))

class GDRegressor:
  def __init__(self, learning_rate, epochs):
    self.m=100
    self.b=-120
    self.lr=learning_rate
    self.epochs=epochs

  def fit(self,x,y):
    for i in range(self.epochs):
      loss_slope_b=-2*np.sum(y-self.m*x.ravel()-self.b)
      loss_slope_m=-2*np.sum(x.ravel()*(y-self.m*x.ravel()-self.b))
      self.b=self.b-(self.lr*loss_slope_b)
      self.m=self.m-(self.lr*loss_slope_m)
      y_pred4=m*x+b
    print(self.b)
    print(self.m)

  def predict(self,x):
    return self.m*x+self.b

gd=GDRegressor(0.001,100)

gd.fit(x,y)

gd.predict(x)