# -*- coding: utf-8 -*-
"""Linear Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YCh1cwifsj29RiLEHAQrA0ngq5brVH_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('student_info.csv')
df

df.head()

df.info()

df.isnull().sum()

df["study_hours"]=df["study_hours"].fillna(df["study_hours"].mean())

df.isnull().sum()

plt.scatter(df.study_hours,df.student_marks)
plt.title("study_hours vs student_marks")
plt.xlabel("study_hours")
plt.ylabel("student_marks")

x=df[["study_hours"]]
y=df["student_marks"]
print(x)
print(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=51)

from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(x_train,y_train)

x_test.head()

model.predict(x_test)

y_test.head()

model.score(x_test,y_test)

plt.scatter(df.study_hours,df.student_marks)
plt.plot(df.study_hours,model.predict(x),color="green")
plt.title("study_hours vs student_marks")
plt.xlabel("study_hours")
plt.ylabel("student_marks")

import seaborn as sns
sns.regplot(data=df,x="study_hours",y="student_marks")
sns.set_style("darkgrid")

# checking the regression equation
def student_marks1(student_hour):
   predict=model.predict([[student_hour]])
   return predict

student_marks1(7)

m=model.coef_
m

c=model.intercept_
c

ans=7*m+c
ans

"""# Multiple linear Regression

"""

df1=pd.read_csv("/content/Student_Performance (2).csv")
df1

df1.info()

df1["Extracurricular Activities"]=df1["Extracurricular Activities"].map({"Yes":1,"No":0})
df1

df1.info()

x=df1.drop(["Performance Index"],axis=1)

x.shape

x.head()

y=df1["Performance Index"]
y.head()

y.shape

from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LR.predict(x_test)

accuracy=LR.score(x_test,y_test)*100
accuracy

intercept=LR.coef_
intercept

slope=LR.intercept_
slope