# -*- coding: utf-8 -*-
"""SuperMarket_Basket_analysis_Using _apriori_algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BBlmH51bMFwToB52Eigm-HiJZ2FSuc9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

df=pd.read_csv("/content/test2.csv")
df

df_Binary= df.replace({'t': True, np.nan: False})
df_Binary.head()

from mlxtend.frequent_patterns import apriori
frequent_itemsets=apriori(df_Binary,min_support=0.1,use_colnames=True)
frequent_itemsets

from mlxtend.frequent_patterns import association_rules
confidence= association_rules(frequent_itemsets,metric="confidence",min_threshold=0.1,num_itemsets=2)
confidence

confidence.columns

result=confidence[['antecedents', 'consequents','support', 'confidence', 'lift']]
result

result1=result[result.lift>1]
result1

result2=result[result.lift==1]
result2

result1=result[result.lift<1]
result1