# -*- coding: utf-8 -*-
"""Mall_Customer_Segmentation using (Agglomerative_Hierarchical_Clustering)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKcELqFtKFjQ27rpv6jm75kAEVsjFWnD
"""

import kagglehub
from kagglehub import KaggleDatasetAdapter
file_path = "Mall_Customers.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "vjchoudhary7/customer-segmentation-tutorial-in-python",
  file_path,)

print("First 5 records:", df.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df.head()

import plotly.express as px
x = df['Annual Income (k$)']
y = df['Spending Score (1-100)']
z = df['Age']

fig = px.scatter_3d(df, x='Annual Income (k$)', y='Spending Score (1-100)', z='Age', color='Age',
                    title='Interactive 3D Scatter Plot of Annual Income, Spending Score, and Age',
                    labels={'Annual Income (k$)': 'Annual Income (k$)', 'Spending Score (1-100)': 'Spending Score (1-100)', 'Age': 'Age'})

fig.update_layout(scene = dict(
                    xaxis_title='Annual Income (k$)',
                    yaxis_title='Spending Score (1-100)',
                    zaxis_title='Age'))
plt.fig()
fig.show()

plt.scatter(df['Annual Income (k$)'],df['Spending Score (1-100)'],color='b')

Dataset=df.iloc[:,-2:]
Dataset

"""**Finding the optimal number of clusters using the dendrogram**"""

import scipy.cluster.hierarchy as sch
dendo=sch.dendrogram(sch.linkage(Dataset,method="single"))
plt.title("Dendogram Plot")
plt.ylabel("Smallest Distance")
plt.xlabel("Customers")
plt.xticks(list(range(0,2500,500)))
plt.show()

import scipy.cluster.hierarchy as sch
dendo=sch.dendrogram(sch.linkage(Dataset,method="complete"))
plt.title("Dendogram Plot")
plt.ylabel("Larger Distance")
plt.xlabel("Customers")
plt.yticks(list(range(0,160,10)))
plt.xticks(list(range(0,2500,500)))
plt.show()

import scipy.cluster.hierarchy as sch
dendo=sch.dendrogram(sch.linkage(Dataset,method="average"))
plt.title("Dendogram Plot")
plt.ylabel("Average Distance")
plt.xlabel("Customers")
plt.yticks(list(range(0,70,5)))
plt.xticks(list(range(0,4000,2000)))
plt.show()

import scipy.cluster.hierarchy as sch
dendo=sch.dendrogram(sch.linkage(Dataset,method="ward"))
plt.title("Dendogram Plot")
plt.ylabel("Optimal Distance")
plt.xlabel("Customers")
plt.yticks(list(range(0,440,20)))
plt.xticks(list(range(0,4000,2000)))
plt.show()

from sklearn.cluster import AgglomerativeClustering
Her_cluster=AgglomerativeClustering(n_clusters=5,metric='euclidean',linkage='ward')
y_pred=Her_cluster.fit_predict(Dataset)
y_pred

Dataset["Cluster"]=y_pred
Dataset

df0=Dataset[Dataset.Cluster==0]
df0

df1=Dataset[Dataset.Cluster==1]
df1

df2=Dataset[Dataset.Cluster==2]
df2

df3=Dataset[Dataset.Cluster==3]
df3

df4=Dataset[Dataset.Cluster==4]
df4

plt.scatter(df0['Annual Income (k$)'],df0['Spending Score (1-100)'],color='r',label='Cluster-1')
plt.scatter(df1['Annual Income (k$)'],df1['Spending Score (1-100)'],color='b',label='Cluster-2')
plt.scatter(df2['Annual Income (k$)'],df2['Spending Score (1-100)'],color='g',label='Cluster-3')
plt.scatter(df3['Annual Income (k$)'],df3['Spending Score (1-100)'],color='y',label='Cluster-4')
plt.scatter(df4['Annual Income (k$)'],df4['Spending Score (1-100)'],color='m',label='Cluster-5')
plt.legend()
plt.show()